### ISSUE TITLE
Error creating ragdoll for class net.minecraft.class_1472

### ISSUE THREAD

**Issue by Steveplays28** [Steveplays28/steve-smp-s5-reloaded#4]
Caused by: Physics Mod

```
[14:26:29] [Render thread/INFO]: [STDERR]: error creating ragdoll for class net.minecraft.class_1472
 [14:26:29] [Render thread/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index (6) is greater than or equal to list size (6) [14:26:29] [Render thread/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:411) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.Ragdoll.addConnection(Ragdoll.java:72) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.RagdollMapper.getCuboids(RagdollMapper.java:157) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.RagdollMapper.getCuboids(RagdollMapper.java:171) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.RagdollMapper.getCuboids(RagdollMapper.java:163) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.RagdollMapper.getCuboids(RagdollMapper.java:171) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.VanillaRagdollHook.map(VanillaRagdollHook.java:362) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ragdoll.RagdollMapper.map(RagdollMapper.java:43) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:576) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$emo000$handleRemoveEntities(class_634.java:11024) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_11095(class_634.java) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2716.method_11764(class_2716.java:31) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2716.method_11054(class_2716.java:9) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2600.method_11072(class_2600.java:22) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.redirect$bae000$redirectExecuteTask(class_1255.java:1021) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:131) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:116) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1129) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:768) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244) [14:26:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:475) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [14:26:29] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [14:26:29] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) 
```

**Comment by Steveplays28** [comment]
Removed physics mod, fixed
